### ISSUE TITLE
Undocumented build dependencies

### ISSUE THREAD

**Issue by stefanv** [phosphorjs/phosphor#1]
I needed to install the following on my system before I was able to build phosphor:

```
gulp-cached, gulp-concat, gulp-cssmin, gulp-header, gulp-jshint, gulp-rename, gulp-streamify, gulp-uglify, vinyl-source-stream
```

**Comment by sccolbert** [comment]
the `npm-install` command should have covered that and automatically installed those dependencies. Did you follow the readme verbatim?
