### ISSUE TITLE
Feature request: scrollspy

### ISSUE THREAD

**Issue by SylvainCorlay** [phosphorjs/phosphor#106]
In Jupyterlab, the content of most plugins is scrollable (command palette, notebook, welcome page).

It would be nice to have a scrollspy feature in order to enable a top border or a shadow when the content is scrolled.

Cf jupyter.org screenshot below:

![after](https://cloud.githubusercontent.com/assets/2397974/16652689/34bd3a42-441a-11e6-8b7d-4dfba13fb22c.gif)

**Comment by sccolbert** [comment]
Is there something in Phosphor preventing you from doing this now in your own code, or are you just asking for a convenience API?

**Comment by SylvainCorlay** [comment]
The jquery code for the jupyter.org is rather simple. I guess 

````Javascript
$(window).on("scroll", function() {
    if($(this).scrollTop()>0){
        $(".navbar").addClass("navbar-scroll");
    } else {
        $(".navbar").removeClass("navbar-scroll");
    }
});
```

I wanted to add something like this (without jqeury) to the about plugin an realized it is a more general thing than this specific plugin. Would this be a phosphor-level thing?

**Comment by SylvainCorlay** [comment]
Or I guess it is fine to add it for each plugin...

**Comment by sccolbert** [comment]
That jquery is nothing special. Here's a non-jq version:

```
widget.node.addEventListener('scroll', () => {
  widget.addClass('thing', widget.node.scrollTop > 0);	
});
```

**Comment by sccolbert** [comment]
I don't think we need a function in Phosphor for that simple line.
