### ISSUE TITLE
Docs build.

### ISSUE THREAD

**Issue by Carreau** [phosphorjs/phosphor#11]
More a question than an issue. 

I looked at many options to (auto)build a pretty main page for phosphor, that would give a short intro, 
and rebuild works on travis

JS-Based one are pretty much do everything yourself, especially template and design. 

The more "out of the box" one, not enough out of the box is jekyll, which is ruby-based, 
and I guess you will have something against it. 

Thoughts ?

**Comment by Carreau** [comment]
WIP : https://github.com/Carreau/phosphor-website, 

Deployed [here](http://carreau.github.io/phosphor-website/about/) for now.

**Comment by Carreau** [comment]
@sccolbert can you create an empty repository in the phosphorjs org named `phosphorjs.github.io` I'll make a pull request to it to host the Phosphor website and docs automatically with Travis.

**Comment by sccolbert** [comment]
Done. https://github.com/phosphorjs/phosphorjs.github.io

Sorry I haven't commented on this yet, I've been slammed.

**Comment by sccolbert** [comment]
You have read/write access to that repo now.

**Comment by Carreau** [comment]
Thanks, I'm almost done having it working locally and is stealing some of your comments on  other issues to fill in the main website pages.
