### ISSUE TITLE
source code for example?

### ISSUE THREAD

**Issue by vrmerlin** [phosphorjs/phosphor#128]
Is there a project file and source code available for this example?

http://phosphorjs.github.io/examples/dockpanel/

I can look at the code in the browser, but the javascript is all stuffed into a bundle.js and isn't very digestible. I was hoping there is a starter project that generates this (is that typescript code in the source window?).

Thanks,
John

**Comment by jjrv** [comment]
The example project file [`tsconfig.json`](https://github.com/phosphorjs/phosphor/blob/282a8ba6d542ce27ac583a3029f0dbd52d17228f/example/tsconfig.json) specifies no source files, so it will include all `.ts` files in that directory. There is only [`index.ts`](https://github.com/phosphorjs/phosphor/blob/282a8ba6d542ce27ac583a3029f0dbd52d17228f/example/index.ts) which contains the source code for the example. It imports the actual widgets from `../lib`.

**Comment by afshin** [comment]
What @jjrv said is exactly right. In addition, the `DockPanel` portion of the example that you're looking for is here: https://github.com/phosphorjs/phosphor/blob/282a8ba6d542ce27ac583a3029f0dbd52d17228f/example/index.ts#L299-L312

**Comment by afshin** [comment]
The previously separated phosphor projects have been frozen at whichever version they were at before all the projects were merged into this repo so that they would not disappear from `npm`, but this repository is the main phosphor library with all of its widgets, utilities, data structures, etc.

**Comment by jjrv** [comment]
Might be a good idea to add a readme to the old projects, explaining the situation.

**Comment by afshin** [comment]
@jjrv That's a good idea. We'll probably do that when phosphor 1.0 is released (or possibly sooner).

**Comment by afshin** [comment]
cc: @sccolbert

**Comment by vrmerlin** [comment]
Ok, thanks, that was a big help. It took a bit of playing around, but I now have my "own" project that copies your example (and pulling in your repository), and give me the docker mechanics (and the TypeScript API) in Electron that I was hoping for.

This is FANTASTIC. You guys are doing great work -- I played with half a dozen docker libraries, and this definitely behaves the best. I'll try to help things along as I can.

Do you have a timeframe for the 1.0 release? Days or months away...?

John

**Comment by sccolbert** [comment]
@vrmerlin thanks for the kind words!

We're probably a month or so out from 1.0, a week or so from a `0.9`.

**Comment by sccolbert** [comment]
On other point of order is that current example in this repo is basically a playground for me to test and validate new functionality as I add it. Once I have all the 1.0 pieces ready, I'll write a bunch of separate examples for each component.

**Comment by sccolbert** [comment]
This question seems to be sufficiently answered. Closing.
