### ISSUE TITLE
`<div>` vs `<span>` in content items...

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor#131]
Still not sure we have the right from a semantics perspective. 

cf #50 about `<a>` tags

**Comment by jasongrout** [comment]
Just curious: what was the decision?

**Comment by sccolbert** [comment]
Keeping things as-is using `<div>`.

We use `<span>` in labels to highlight characters. So treating label, icon, shortcut etc as separate semantic "things" is okay. Deciding whether to use `<a>` tags by default would require too much research, and if people really don't like the defaults, they can now easily write their own renderer.
