### ISSUE TITLE
sizing.js should use parseFloat

### ISSUE THREAD

**Issue by svenefftinge** [phosphorjs/phosphor#135]
The computation of box sizes etc. should be precise and use doubles instead of ints.
E.g. for me in chrome the jupyterlab border of a notebook editor is 0.909091px which gets rounded to 0 by parseInt.

**Comment by jasongrout** [comment]
parseFloat, right? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat

**Comment by sccolbert** [comment]
why does jlab have a fractional border?

**Comment by svenefftinge** [comment]
It is defined as a border of 1px but it becomes something slightly less when zooming (in chrome).

**Comment by sccolbert** [comment]
Relevant links (will add as I find more):
https://bugzilla.mozilla.org/show_bug.cgi?id=588026

**Comment by sccolbert** [comment]
fixed in https://github.com/phosphorjs/phosphor/commit/92e888dd7e217cd39c984bf407413df9220c418e
