### ISSUE TITLE
Audit use of `delete` with `dataset` objects

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor#138]
I think `vdom` might use this in places. cf #137

**Comment by minrk** [comment]
The only cases I found were:

[`delete resultMap[id]`](https://github.com/phosphorjs/phosphor/blob/0.6.1/src/ui/application.ts#L656) in application

and

[`delete this._commands[id]`](https://github.com/phosphorjs/phosphor/blob/0.6.1/src/ui/commandregistry.ts#L87) in commandregistry

which don't look like they should be affected by the property issue, but I'm not 100% sure.
