### ISSUE TITLE
Proposal: Resolve a token when it becomes available

### ISSUE THREAD

**Issue by blink1073** [phosphorjs/phosphor#146]
In discussion in NYC this week, we saw a use case for a function on the `Application` that resolves a token if and when it is actually resolved.  The use case is for a plugin that will use an interface if it is available, but does not explicitly require it to be available.  An example is a main menu plugin may not be strictly required by the plugin, but we would like to add an entry to it if it is available.  The signature may look like:

``` typescript
/**
 * Resolve a service of a given type if it becomes available.
 * 
 * @param token - The token for the service type of interest.
 *
 * @returns A promise which resolves to an instance of the requested
 *   service when it is registered.
 */  
weakResolveService<U>(token: Token<U>): Promise<U> {

}
```

**Comment by blink1073** [comment]
cc @jasongrout @ivanov

**Comment by sccolbert** [comment]
I can see the utility. The semantics need to fleshed out. Would this be something that can optionally required by a plugin spec? (that seems difficult to work out) Or something that an *already activated* plugin can require from the app, using a method like you named? (that seems easier)

**Comment by blink1073** [comment]
We preferred the latter, because we should be resolving the plugin when its explicitly required interfaces are available, meaning you'd still need a way to resolve the others.  It seemed intuitive to call a method on the application that returned a promise for the thing we wanted from within the plugin.

**Comment by jasongrout** [comment]
> We preferred the latter

I think so too. Of course, that also provides another approach to resolving dependencies, so it's strictly more powerful than the current `requires` field of the plugin definition. However, I think documentation and education will help people use the (usually clearer) way of resolving dependencies using our current mechanism.

**Comment by blink1073** [comment]
It turns out the existing `resolveService` [method](https://github.com/phosphorjs/phosphor/blob/47fce2da39ad2397af17b0e01a35c7560575939a/src/ui/application.ts#L212) already has the semantics we want.

**Comment by jasongrout** [comment]
Perhaps the documentation at https://github.com/phosphorjs/phosphor/blob/master/%40phosphor/application/src/index.ts#L305 could be updated to note this usecase for user code calling the function?

**Comment by jasongrout** [comment]
My point being that the documentation implicitly discourages a user from calling the function. 

Perhaps something like "Usually the required services for the user's plugins will be resolved automatically when the plugin is activated, without a user's plugin explicitly calling this function. If the user's plugin needs to run code if and when a service becomes available without explicitly depending on the service, user code may call this method directly."

**Comment by sccolbert** [comment]
Hmm, seems like the concept of "optional services" would be good to have.

**Comment by blink1073** [comment]
Ah, as a top level plugin item that can be null or a token?

**Comment by sccolbert** [comment]
I updated the comment to be more descriptive.

**Comment by sccolbert** [comment]
I was thinking an `optional` field on `IPlugin` which holds tokens. If those tokens are available at startup, they'll be resolved, otherwise you'll get null. The optional services would come after the required services in `activate`

**Comment by blink1073** [comment]
Yeah, that was what I meant but failed to articulate ;).

**Comment by sccolbert** [comment]
If an optional service is available, but the plugin which provides it fails to resolve, should the plugin which requested it get `null`, or should that plugin fail to activate?

**Comment by blink1073** [comment]
How would it be available if the provider fails to resolve?
