### ISSUE TITLE
Client performance when moving panels 

### ISSUE THREAD

**Issue by mrocklin** [phosphorjs/phosphor#148]
Moving panels around in my browser appears to be more performance intensive than I would have expected.  I can easily push chrome to 100% usage by dragging borders between panels around.  Is this expected?

**Comment by sccolbert** [comment]
It really depends on the contents *in* the panels. The act of resizing the panels themselves is `< 1ms` on my machine. If you are reflowing lots of stuff *within* the panels, the cost can add up.

Try running this example and seeing how it affects your CPU usage.  It's negligible on my machine.

**Comment by sccolbert** [comment]
Also, the chrome profiling dev tools can help you pin down the costs during resize with nice flame charts.

**Comment by mrocklin** [comment]
I'm totally out of my element here when it comes to browser performance, but one thought would be to throttle resize events to occur no more often than every 20ms or something.

**Comment by sccolbert** [comment]
Splitter resizes are *already* throttled on animation frames (which let's the browser pick the optimal refresh). My hunch here is that you have content in your panels which takes a long time for the browser to relayout due to the resize. What are you displaying in your panels?

**Comment by mrocklin** [comment]
It first arose when when dealing with Bokeh plots (which would make sense as expensive) but I can reproduce with a notebook and a terminal

**Comment by sccolbert** [comment]
This is almost certainly inline reflows due to resizing the notebook, and not an inherent performance problem with Phosphor. Can you please open an issue on JLab so we can track it down there?

**Comment by mrocklin** [comment]
Way ahead of you: https://github.com/jupyter/jupyterlab/issues/958  :)
