### ISSUE TITLE
Docs don't build

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor#157]
I couldn't get TypeDoc `^0.5.0` to build with TS 2, because it doesn't seem that TypeDoc accepts the full suite of tsconfig options (like which built-in libs to use). I also didn't spend a bunch of time on it, since docs have been broken for a while.

cc @blink1073

**Comment by jasongrout** [comment]
You're right, typedoc chokes on tsconfig TS2-specific options. For JLab, we don't use the tsconfig - we just let typedoc use default settings to generate docs for all of the `.ts` files. Apparently typedoc 0.5.1 will ignore TS2 options (see https://github.com/TypeStrong/typedoc/pull/308). I haven't tested that yet, though.

**Comment by blink1073** [comment]
Note: support is still not there: https://github.com/TypeStrong/typedoc/issues/301

**Comment by blink1073** [comment]
Progress!  https://github.com/TypeStrong/typedoc/pull/449

**Comment by jasongrout** [comment]
I wonder if https://github.com/Microsoft/TypeScript/pull/13940 (slated for TS 2.3, I believe) will make it easier to have a documentation generator as a source code transformation.
