### ISSUE TITLE
Latest Dockpanel behavior

### ISSUE THREAD

**Issue by ellisonbg** [phosphorjs/phosphor#159]
@sccolbert just updated to the latest JupyterLab that is based on the latest stable phosphor. In JupyterLab the visual design of the dock panel is messed up, but that can be fixed on the Jlab side of things. For reference here is a screenshot:

<img width="819" alt="screen shot 2016-11-04 at 2 43 26 pm" src="https://cloud.githubusercontent.com/assets/27600/20023580/3deecc10-a29e-11e6-9339-e6db9d2ae29a.png">

We will update our style on the JupyterLab side to fix these things. The other big difference is the behavior of the drag areas in the dock panel. Those are summarized from (https://github.com/phosphorjs/phosphor/pull/155) here:

Summary of behavioral changes:

1. There is now a drop zone on top of the tab bars.
2. There is no more center drop zone on a widget.
3. You must hold shift while dragging to activate the border drop zones.
4. Clicking on a tab now activates the widget, even if the tab is already current.

I can see where 1 and 2 are coming from. The old center drag area wasn't completely obvious to new users - we saw this in users tests. But those results were not so dramatic that the new behavior is clearly better. The right way to test this is in a user test. I am willing for us to "try it out ourselves" for a bit, but I think we should treat this behavior change and provisional until we are convinced it is better.

I am guessing that 3 happened because the old border drop zones were interfering with the new tab drop zones. From an implementation perspective, I understand. But from the usability perspective, the new behavior is not discoverable without us telling users about the behavior. Even then, it is really subtle to figure out (when can you add the shift modifier for example). The old drag zones were nice because the users didn't have to be aware of the subtle nesting/border questions - they just moved things around to get the layout they wanted. Now they have be aware of the arbitrary (from their perspective) differences between nesting versus border drop zones.

**Comment by sccolbert** [comment]
@ellisonbg I'm not sure what the purpose of this issue is. Do you want me to take some action?

If we have tab drop zones, which user tests and issue feedback suggest that we do, then we *must* have a way to distinguish between tab zones and edge zones which overlap. No one has yet suggested a better alternative than holding `Shift`, but I'm all ears for more ideas.

**Comment by sccolbert** [comment]
Just went through your comments on Gitter about this. It seems like there's some confusion about what/why changes were made. The behavior as it exists now is not "broken" per-se, it's behaving as designed. Maybe we need to have a discussion about whether that design is incorrect.

**Comment by jjrv** [comment]
An alternative to holding shift might be that dragging towards the top of the window (or other edges if they contain tab bars), the rest of the content slides slightly in the opposite direction to expose a new drop area outside the tabs. Would have to test if the idea works in practice, but something like how two-finger scrolling past document beginning and end in OS X.

In more detail: If there's a tab bar at the top, you can drag a tab down to the middle of the screen without anything special happening. Then while dragging back up, the whole page scrolls gradually down at the same time, by maybe total 24-32 pixels by the time the mouse reaches the top. It's still easy to drop the tab back in the tab bar (now slightly lower than before) or to the new space above it. Dragging the tab back downwards scrolls the page back again, so it's possible to drag all the way to the bottom edge as before.

**Comment by sccolbert** [comment]
@jjrv What you describe is a very complex interaction, and would involve tracking and discerning mouse movement history. That's too much complexity IMO.
