### ISSUE TITLE
scrolling within a docking pane?

### ISSUE THREAD

**Issue by vrmerlin** [phosphorjs/phosphor#160]
I'm attempting to use Angular 2 with the Phosphor Docking Widgets. The idea is that the widget creates web content that is a custom tag, and that tag is then replaced (in the onUpdateRequest() call) by Angular 2 to populate the content. It seems to be working, in that my widget displays the HTML content that I expect. I think it has the potential to be a really cool architecture for providing a variety of "stand alone" apps within a common docking framework.

The problem is that I should be seeing scrollbars within the widget pane (since I have more content than would fit), and they aren't there. Instead, the content is simply cut off. Here is my Widget code below. Any ideas what I might be doing wrong? I see there is an onResize() method I could implement, but I'm not sure what to put inside it.

```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { Message }            from 'phosphor/lib/core/messaging';
import { Widget, WidgetFlag, ResizeMessage } from 'phosphor/lib/ui/widget';

import { AppInfoModule } from './app-info.module';

export class AppInfoWidget extends Widget {

  static createNode(): HTMLElement {
    var node = document.createElement('app-info');
    return node;
  }

  constructor() {
    super({ node: AppInfoWidget.createNode() });
    this.addClass('AppInfoWidget');
    this.title.label = "App Information";
    this.title.closable = true;
  }


  protected onAfterAttach(msg: Message): void {
    this.update();
  }

  protected onUpdateRequest(msg: Message): void {

    const platform = platformBrowserDynamic();
    platform.bootstrapModule(AppInfoModule);

  }
}
```

**Comment by sccolbert** [comment]
To start, is angular *replacing* the `app-info` node on the page, or is it simply adding content to it. If it's the latter, you're fine. Otherwise, you need to create a child `app-info` node on the widget's node, or the widget will refer to the wrong element after angular does the replacement.

Second, a Widget's node has `overflow: hidden` by default. You need update your CSS for that widget to have `overflow: auto`. You don't need to worry about `onResize` for this.

**Comment by vrmerlin** [comment]
Thanks!! I was able to fix it with the overflow  auto.
