### ISSUE TITLE
Tab contents don't hide if they have css setting display with specificity greater than 2

### ISSUE THREAD

**Issue by jasongrout** [phosphorjs/phosphor#164]
Can we add a documentation note mentioning that phosphor hides elements with a selector having attribute specificity of 2? I was running into a case where tab content was showing up when it shouldn't, and it turned out that there was some styling that overrode Phosphor's attempt to hide tab content.

Another option would be to make the tab hiding css at  https://github.com/phosphorjs/phosphor/blob/ed6c10e483a7aeb71bdd116ca870a9162d895662/styles/base.css#L282 use `!important`, but that is strongly recommended against on MDN. Another option would be to wrap tab content in another div that we control, so we can make sure to control the display, but even that doesn't solve the problems of elsewhere in phosphor assuming that you can hide content with a class selector of specificity 2.

**Comment by jasongrout** [comment]
CC https://github.com/ipython/ipywidgets/pull/919 where the issue came up.

**Comment by jasongrout** [comment]
A related issue - if I hide a widget, and put it in a tab panel, then the tab panel may unhide the widget for me. It may be cleaner to have the tab panel embed each of its content widgets inside of a widget it controls, so it can hide/show the content independently of the widget hiding/showing itself.

**Comment by jasongrout** [comment]
> It may be cleaner to have the tab panel embed each of its content widgets inside of a widget it controls, so it can hide/show the content independently of the widget hiding/showing itself.

@sccolbert - thoughts about having tab content wrapped in a widget that the tab panel controls?

**Comment by sccolbert** [comment]
> Can we add a documentation note mentioning that phosphor hides elements with a selector having attribute specificity of 2?

I don't know whether I (we) ever opened an issue on this, but I was talking with the team and we agreed that adding `!important` to the rule for `p-mod-hidden` is reasonable, which would solve this specificity problem.

> thoughts about having tab content wrapped in a widget that the tab panel controls?

:-1: This would be adding an unnecessary level of nesting for everyone all the time. If you need that behavior, you can wrap the widget yourself.

But, if the only complaint is the auto-showing of widgets when added to the tab panel, you can control that by changing the `insertBehavior` of the tab panel's `tabBar`.

**Comment by jasongrout** [comment]
> 👎 This would be adding an unnecessary level of nesting for everyone all the time. If you need that behavior, you can wrap the widget yourself.

I was debating between the badness of an automatic (internal) wrapper widget vs the `!important` selector. I thought you'd never go for the `!important` css...

**Comment by sccolbert** [comment]
fixed in master

**Comment by jasongrout** [comment]
Thanks. We've also added that specifically for tabs to the ipywidgets project in the meantime, and it's worked great: https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/css/widgets-base.css#L899

**Comment by sccolbert** [comment]
In master, I've marked anything using `p-mod-hidden` to hide stuff as `!important`.
