### ISSUE TITLE
Drag images offset on scrolled pages

### ISSUE THREAD

**Issue by vidartf** [phosphorjs/phosphor#165]
On pages that can scroll, the location of the drag image gets offset when scrolling:

![phosphor-drag-offset](https://cloud.githubusercontent.com/assets/510760/20801360/e0137f40-b7e8-11e6-855b-f42d3a44c5d7.gif)

I assume that the actual position is off by `window.pageOffsetX`/`pageOffsetY`, but I cannot directly tell if this is a bug with my code or with phosphor.

**Comment by sccolbert** [comment]
This is a bug. I didn't consider page scrolling when I wrote that code. Thanks!

**Comment by vidartf** [comment]
Much cleaner fix than the workaround I ended up using!
