### ISSUE TITLE
React examples w/ JSX?

### ISSUE THREAD

**Issue by george-norris-salesforce** [phosphorjs/phosphor#166]
Awesome that there is this example ➡️➡️  http://phosphorjs.github.io/examples/todomvc/#/ but most React apps use JSX. It would really useful to have an example which uses JSX.

**Comment by sccolbert** [comment]
Thanks for the interest!

There are two API calls to `React` in that example. Only one would go away with JSX. I don't see much value in updating the example for that.

I'm not really interested in making React examples, beyond showing how the two frameworks can be integrated. I feel this example achieves that goal sufficiently.
