### ISSUE TITLE
Issues with drag and drop on DockLayout

### ISSUE THREAD

**Issue by mladen107** [phosphorjs/phosphor#170]
DockPanel drag and drop event handlers (beside on 'p-dragenter') don't check MIME type which can conflict with other drag and drop logic on container element.

I created fork since I want to keep using 0.6.1 but I think you should fix it too in future release.

This is what fixed issues for me:
https://github.com/phosphorjs/phosphor/compare/master...mladen107:master

**Comment by sccolbert** [comment]
If the mime type is incorrect, it doesn't accept the event, so it shouldn't get any further drag/drop events (which means it doesn't need to check the mimetype). Can you be a bit more specific with an example?

**Comment by sccolbert** [comment]
https://github.com/phosphorjs/phosphor/blob/master/src/ui/dockpanel.ts#L413-L418

If the default is not prevented on `p-dragenter`, no further drag/drop events are sent. If they are being sent, that's probably a bug.

```typescript
  private _evtDragEnter(event: IDragEvent): void {
    // If the factory mime type is present, mark the event as
    // handled in order to get the rest of the drag events.
    if (event.mimeData.hasData(FACTORY_MIME)) {
      event.preventDefault();
      event.stopPropagation();
    }
  }
```

**Comment by mladen107** [comment]
I have _div_ element that **contains** dockpanel. My _div_ element has attached listeners to `'p-'` drag/drop events. Until I made _my fix_ on each drag/drop event handler of dockpanel, dockpanel was handling all other events beside 'p-dragenter'. After my fix I finally started receiving events on _div_ and it didn't break dockpanel's default logic.

So I guess there is bug in drag/drop machinery. 

Also previously I had native (html5) drag and drop. I didn't have to use `dragenter` to make working `dragover `and `drop` events(tested on chrome, firefox, safari and edge). I didn't read HTML5 drag/drop spec so I'm not sure what should be correct behavior.

**Comment by mladen107** [comment]
Just to add, I dockpanel was reacting on mimeData that doesn't contain data for FACTORY_MIME key. That's the easiest way to reproduce bug.

**Comment by sccolbert** [comment]
I'm unable to reproduce what you describe. If I drag over a dock panel with a mimedata which doesn't contain the `'application/vnd.phosphor.widget-factory'` mimetype, the only drag event that the dock panel receives is `p-dragenter`.

**Comment by sccolbert** [comment]
If you have a self-contained simple example that I can run which reproduces the problem, please open a new issue.
