### ISSUE TITLE
A need for AfterHide and BeforeShow messages.

### ISSUE THREAD

**Issue by afshin** [phosphorjs/phosphor#171]
Currently, there are `after-show` and `before-hide` messages (and thus interceptable hooks) on widgets. Their counterparts, `after-hide` and `before-show` would be helpful.

As a use case, JupyterLab has a message hook that catches `before-hide` but needs for the widget's `isHidden` flag to be set to `true` (so, it needs to know the hide has completed). Currently it does this by catching `WidgetMessage.BeforeHide` and then waiting for the next animation frame, but ideally it would just listen for `WidgetMessage.AfterHide`.

Here is the code in question:

```typescript
// If the help widget visibility changes, update the tracker.
installMessageHook(iframe, (iframe: IFrame, msg: Message) => {
  switch (msg) {
    case WidgetMessage.AfterShow:
    case WidgetMessage.BeforeHide:
      // Wait until hide has completed.
      requestAnimationFrame(() => { tracker.save(iframe); });
      break;
    default:
      break;
  }
  return true;
});
```

https://github.com/jupyterlab/jupyterlab/blob/8bfffce6c45f161019c20016743bce4f4d6fda83/src/help/plugin.ts#L151-L163

**Comment by sccolbert** [comment]
fixed in 1.0
