### ISSUE TITLE
VNode event handlers

### ISSUE THREAD

**Issue by akosyakov** [phosphorjs/phosphor#174]
Should not a first argument of an event handler be `this` of `HTMLElement` type or of a type of the target element? For example:
```ts
    onchange?: (this: HTMLElement, ev: Event) => any;
```

**Comment by sccolbert** [comment]
That's probably a good idea. Fixed and will roll out with 1.0: https://github.com/phosphorjs/phosphor/commit/afe98188af08cb9a37d08bf7701a8d563ac282ac
