### ISSUE TITLE
VNode: mapping to DOM

### ISSUE THREAD

**Issue by akosyakov** [phosphorjs/phosphor#176]
1. How to find a dom node for a given vnode? Something like https://facebook.github.io/react/docs/react-dom.html#finddomnode will be nice.

2. Having something similar as ref callbacks in ReactJS would be nice too:  https://facebook.github.io/react/docs/refs-and-the-dom.html

They are both useful to mix existing js code together with VNode and customizing rendered DOM model.

**Comment by stoplion** [comment]
After realizing JSX does not work so good with the examples.. I ended up using pretty much this.

//this.widgetContent is a ref
const d = ReactDOM.findDOMNode(this.widgetContent);
const w = new Widget();
w.node.appendChild(d);
this.dockPanel.insertTop(w);

**Comment by sccolbert** [comment]
So, in a previous version of this code, I did have `refs`, but then I figured anything `refs` can do can be done with `querySelector` and the appropriate class names and/or ids. Do you have use case which can't be solved with `querySelector` after rendering the content?

**Comment by sccolbert** [comment]
Closing as solved. I'll reopen it if you still have questions.
