### ISSUE TITLE
Reveal vs. Focus (Activate)

### ISSUE THREAD

**Issue by svenefftinge** [phosphorjs/phosphor#177]
Currently, to make widgets visible they get activated and it is implied that a widget sets the focus on some of its elements on activate.

What is the best approach to only reveal a widget but not focus it?
For a use-case imagine debugging, where different editors and lines get revealed highlighted while stepping, but the focus should not jump to the editors.

**Comment by sccolbert** [comment]
I'm a assuming you mean when a tab is clicked. That action (clicking a tab) causes the `tabActivateRequested` signal to be emitted. In response, the `TabPanel` and `DockPanel` will call `.activate()` on the widget associated with the tab which was clicked. That method is a convenience method for posting an `activate-request` message to the widget, which will (when processed) call the `onActivateRequest` message handler of the widget. The default implementation of that method is a no-op. `Widget` subclasses are expect to reimplement that method to "do the right thing" when they get that message. So Phosphor is not focusing these widgets automatically, it's something the subclass is doing.
