### ISSUE TITLE
Add input wrapper styling

### ISSUE THREAD

**Issue by cameronoelsen** [phosphorjs/phosphor#181]
This is an issue connected to https://github.com/jupyterlab/jupyterlab/issues/1472 

Currently there is no way to style input field wrappers when the contained input field is active.

**Comment by sccolbert** [comment]
This is fixed in `feature-submodules` and will be released with 1.0. The `CommandPalette` adds a `p-mod-focused` class to itself when the search input has focus. You can use that with a selector:
```css
.p-CommandPalette.p-mod-focused p-CommandPalette-wrapper {
  ...
}
```
