### ISSUE TITLE
Support for both capture and bubble phase events in Keymap

### ISSUE THREAD

**Issue by afshin** [phosphorjs/phosphor#185]
Even though the majority of key bindings can (and should) happen in the bubble phase of events, there are cases where we need capture phase bindings. Can `Keymap` be augmented to support both phases, probably with the default being bubble?

**Comment by sccolbert** [comment]
I'll add this for 1.0 release

**Comment by sccolbert** [comment]
We talked about this, and supporting *both* capturing and bubbling in the same keymap is not tenable. Further, what we *really* want in most cases is to trigger shortcuts on the capturing phase, so I've updated the `Application` object to do that. No changes to the keymap are necessary.

**Comment by svenefftinge** [comment]
I think this is not a good idea, as if I embed a thirdparty component as a widget that itself has contextual keybindings, that are not registered with the command registry the key events are prevented.

Concrete scenario: I use the monaco editor and if I have a suggestion pop up and hit enter to apply a suggestion the event is fetched by a command from an outer component (i.e. Jupyterlab's console:run). As a result a get no keydown event and no chance to consume the event before it is consumed by an outer component. I think for events that do preventDefault the bubbling is more appropriate.

**Comment by svenefftinge** [comment]
For reference https://github.com/phosphorjs/phosphor/commit/f4503e935343dafa71e7df1219c057c6227b5c28

**Comment by afshin** [comment]
@svenefftinge It turns out that having events in the bubble phase is simply going to make having keyboard shortcuts that work on top of editors completely intractable because editors handle keystrokes in the capture phase. So the way we are accommodating both the editor and the global shortcuts is by having very specific selectors on the shortcuts.

Here is an example: I want `Shift Tab` to un-indent a block of text if there is a selection in my text editor and my cursor is in the text editor. But I *also* want `Shift Tab` to launch a tooltip popup in the text editor if I didn't have any text selected. The way we are dealing with this is by having the code editor widget add a class to itself when it has a selection: `jp-mod-has-primary-selection` and that way we can with this selector: `.jp-CodeConsole-prompt .jp-CellEditor:not(.jp-mod-has-primary-selection)` and not worry about that command firing if there is *no* selection.

In your example, I think this should be solved in JupyterLab (or any other application) by basically creating some sort of filtering class like above. So perhaps when there's a suggestion popup, there's a class added to editor `jp-mod-has-deferred-focus` or something like that, and the `console:run` command's selector is amended so that it ignores that: `:not(.jp-mod-has-deferred-focus)`, etc.
