### ISSUE TITLE
Maximization of dock panel content widgets

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor#188]
Still needs discussion about whether to maximize the tab area, or the current tab content.

**Comment by jasongrout** [comment]
I think it would make sense to maximize the tab panel (with tabs showing). Maybe we could have a special case where if we only have on tab in the panel, then we just maximize the tab content.

**Comment by blink1073** [comment]
I'd say only do that if you truly have only one tab panel, or else you have a confusing state trail when you maximize a tab panel and then a tab.

**Comment by sccolbert** [comment]
Fixed in #241

**Comment by rmeshksar** [comment]
Would you please explain how the maximization works?
What I would like to do it that in the dock panel, only one widget can be maximized and it occupies the entire dock panel. When minimized, it gets back to its previous position.
Is it possible save the layout before maximization, then fabricate the layout the way that only one panel with one tab is displayed, and when minimized, restore the saved layout?

**Comment by sccolbert** [comment]
Set the dock panel to single document mode: `dockPanel.mode = 'single-document'`. Call `activateWidget()` to select the widget you want displayed.

The save/restore you talk about is exactly what we do in JupyterLab via `saveLayout()` and `restoreLayout()`.

**Comment by rmeshksar** [comment]
Thanks, it works great. I am trying to create a renderer for the tab and include a maximize/minimize button and raise an event when clicked. It is getting handled in the higher level to activate the selected widget and change the mode.
I noticed that when it is in single-document the tab disappears. 
Is there any way to still keep it?

**Comment by sccolbert** [comment]
No. Single document mode hides the tab bars entirely. The reason is because if the tab bar is shown, the user will think they can still drag stuff around, but they shouldn't be able to do that in single document mode.

If all you want is to collapse everything into a single tab area, you don't need single document mode. All you have to do is restore a layout which is a single tab area of all the children (or just the children you care about).

This should work (untested):
```typescript

import {
  toArray
} from '@phosphor/algorithm';


let myWidgets = toArray(myDockPanel.widgets());

myDockPanel.restoreLayout({
  main: {
    type: 'tab-area',
    widgets: myWidgets,
    currentIndex: 0
  }
});
```

**Comment by rmeshksar** [comment]
That works great. I just needed to show only one widget which is fine.
One last question. Is there any way to change the TabBar renderer as part of the dock panel?

**Comment by sccolbert** [comment]
You can provide your own `DockPanel.IRenderer`:
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/dockpanel.ts#L971

Which creates tab bars using your custom tab bar renderer:
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/dockpanel.ts#L1189-L1211

Probably simplest to subclass `DockPanel.Renderer` and reimplement `createTabBar()`.

**Comment by nmichaud** [comment]
I have attempted an implementation of a maximize/minimize button (along with a configuration/menu button per tab):

https://nmichaud.github.io/phosphor/

It involved a bit more subclassing than just the TabBar renderer, mainly around handling clicks on the icons and then propagating those into the containing DockPanel.

@rmeshksar I would be interested in seeing your approach.
