### ISSUE TITLE
PanelLayout init causes DOM error

### ISSUE THREAD

**Issue by jasongrout** [phosphorjs/phosphor#191]
Add two widgets to a PanelLayout, then set it to be the layout on a widget. The PanelLayout [init method](https://github.com/phosphorjs/phosphor/blob/fe9d064070eaa680f46285761fabf789451e699c/%40phosphor/widgets/src/panellayout.ts#L190) is called, which in turn calls the [attachWidget method](https://github.com/phosphorjs/phosphor/blob/fe9d064070eaa680f46285761fabf789451e699c/%40phosphor/widgets/src/panellayout.ts#L212) for each widget in turn. However, attachWidget looks up the next widget in the widgets list and uses it as a reference point to [insert the node](https://github.com/phosphorjs/phosphor/blob/fe9d064070eaa680f46285761fabf789451e699c/%40phosphor/widgets/src/panellayout.ts#L222) into the DOM. Since we are looping over the widgets in increasing order in the init method, the later widgets haven't been inserted into the DOM, so we get a "DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."

An easy fix should be to attach widgets in reverse order at https://github.com/phosphorjs/phosphor/blob/fe9d064070eaa680f46285761fabf789451e699c/%40phosphor/widgets/src/panellayout.ts#L189

I found this debugging the ipywidgets TabPanel at https://github.com/jasongrout/ipywidgets/blob/1b0ce201527c86570ec7374f799a46db1dd587f2/jupyter-js-widgets/src/phosphor/tabpanel.ts#L94-L101

**Comment by sccolbert** [comment]
Wow. That's a bad one. Can't believe it went undiscovered until now. I owe a drink.

**Comment by sccolbert** [comment]
Hmm, it seems I used to look up the ref based on the node children, but at some point I changed it to look up the sibling widget. Hunting for why I made that change:
https://github.com/phosphorjs/phosphor/blob/47fce2da39ad2397af17b0e01a35c7560575939a/src/ui/panel.ts#L307

**Comment by sccolbert** [comment]
Here's the commit where I made the change. Unfortunately, no comment as to why. I seem to vaguely recall there was an issue with the old version, but for the life of me, the old version seems fine...
https://github.com/phosphorjs/phosphor/commit/650bef1a87835b6e2915d52db85127727fec9741

**Comment by blink1073** [comment]
Perhaps it was the browser extension adding dom nodes debacle?

**Comment by sccolbert** [comment]
That sounds like it could be it. Going to revert to the old way. Browser extensions which arbitrarily modify the DOM are not supportable anyway (it would completely mess up virtual DOM rendering for example).
