### ISSUE TITLE
Where did all the libraries go?

### ISSUE THREAD

**Issue by imaluengo** [phosphorjs/phosphor#197]
Hello,

I might just arrive in the middle of a migration or something. But I did try to access phosphorjs's documentation:
http://phosphorjs.github.io/docs.html

And all the docs are missing. After checking Github I've just realised that the independent libraries are missing too.

Did I miss some re-structuring of phosphorjs? Any details on this would be highly appreciated, as I might aim to build an application on top of phosphorjs and I would like to know if it is stable enough to do so.

Thank you very much,
Imanol

**Comment by blink1073** [comment]
Hi @imaluengo, we have gone through a couple of iterations, because packaging is so much fun :smile:.  The library started as one `npm` package in this repo.  It was then split into all of the repos in this org.  We attempted to merge it again as one `npm` package in this repo, but have settled on the pattern of having multiple `npm` packages in the same repo (this one).  As the note says, the API docs are forthcoming.  We just made the changeover this week :wink:.

**Comment by imaluengo** [comment]
Hi @blink1073, thank you very much for the quick response! I started playing with phosphorjs about a month ago, and after some busy weeks came back to keep **playing** with it. I was panicking when I saw no documentation haha I'm glad to hear that you are making up your minds and everything is coming back together. So far the framework looks pretty amazing and I love how quick/responsive do the widgets work! Keep up the good work :D

**Comment by sccolbert** [comment]
As Steve mentioned, we just completed a pretty big reorg prior to the 1.0 releases. The new package structure is here: https://github.com/phosphorjs/phosphor/tree/master/%40phosphor

Part of this reorg included updating to TypeScript 2.1, which is not yet supported by the documentation generator we were using, so I had to disable the API docs for the moment. They'll be up again once we get that sorted out.

**Comment by thomasd16** [comment]
Do you have any more information on this at the moment. I would really like to use the library but with the docs missing I am looking at other less complete solutions.

**Comment by blink1073** [comment]
No, we are still waiting on upstream support from TypeDoc.

**Comment by jasongrout** [comment]
I've been reading the actual code files themselves (the code has all the documentation inline), which seems to work okay too.
