### ISSUE TITLE
Some useful variables hidden in the dragdrop API

### ISSUE THREAD

**Issue by jjrv** [phosphorjs/phosphor#198]
These are one-liners to implement, hopefully they could be considered:

- [ ] `IDragEvent` could contain the `Drag` object or at least its `dragImage`.
- [ ] `DockPanel` could pass itself as `source` to the `Drag` objects it creates, so anyone receiving the drag events knows where they come from.

**Comment by jjrv** [comment]
These would help clean up the code of [phosphor-float-area](https://github.com/charto/phosphor-float-area#readme).

**Comment by sccolbert** [comment]
Could you give an example use case of what they would help with?

**Comment by sccolbert** [comment]
For the drag image, you can use a document query to get it:

`document.body.querySelector('.p-mod-dragImage')`

**Comment by jjrv** [comment]
Reminds me of jQuery... But if that's the official way to do it, fine. It can always be fetched and cached on `p-dragenter`.
