### ISSUE TITLE
http://phosphorjs.github.io/phosphor-messaging/api 404

### ISSUE THREAD

**Issue by paul-shannon** [phosphorjs/phosphor#203]
Hoping to learn how to pass messages between two jupyterlab notebooks using phosphorjs native protocols, I started reading

     http://phosphorjs.github.io/docs.html

then found these links led nowhere:

     http://phosphorjs.github.io/phosphor-messaging/api
     http://phosphorjs.github.io/phosphor-signaling/api

"Page Not Found  Sorry, but the page you were trying to view does not exist."

**Comment by sccolbert** [comment]
Thanks. We just finished a fairly large refactoring, and the docs are out of date. Unfortunately, the doc tool we were using is not yet compatible with the most recent version of TypeScript. This will be fixed asap.

**Comment by sccolbert** [comment]
Fixed in Fixed in #266.
