### ISSUE TITLE
Angular CLI/Webpack not working with Phosphor

### ISSUE THREAD

**Issue by vrmerlin** [phosphorjs/phosphor#207]
We've had great luck using Angular2 and Phosphor together, using the SystemJS loader. But the Angular industry seems to have moved to Angular-CLI and Webpack, so we are trying to do the same change.

Unfortunately, I'm running into a show-stopping problem. From what I've learned about Angular CLI, it looks like I need to add the Phosphor scripts I use to the .angular-cli.json file, like so:

```
      "styles": [
        "styles.css",
        "../node_modules/phosphor/styles/base.css"
        ],
      "scripts": [
        "../node_modules/phosphor/lib/core/messaging.js",
        "../node_modules/phosphor/lib/algorithm/iteration.js",
        "../node_modules/phosphor/lib/ui/widget.js",
        "../node_modules/phosphor/lib/ui/boxpanel.js",
        "../node_modules/phosphor/lib/ui/dockpanel.js",
        "../node_modules/phosphor/lib/ui/widget"
      ],
```

Adding these .js files made a lot of my browser errors go away, but I'm still getting the error ``Uncaught Error: Cannot find module '../algorithm/iteration'``.   That relative path is in the Phosphor code, in a number of places. Has anyone had any luck getting Webpack and Phosphor working together?

Thanks,
John

**Comment by sccolbert** [comment]
We use webpack exclusively for Phosphor example and tests, and also for JupyterLab.

Be advised, that we recently split phosphor up into `@phosphor/*` namespace packages, all managed under this repo.

@blink1073 can maybe link you to an example webpack config which consumed phosphor as an npm-installed package, rather than a local package.

**Comment by sccolbert** [comment]
I'm going to close this because it's not relevant for the Phosphor code base, but feel free to keep exchanging ideas.

**Comment by blink1073** [comment]
Here's an [example](https://github.com/jupyterlab/jupyterlab/blob/9b5462aa2ebbbef8e06b587327fde5598b6c79b7/test/webpack.conf.js).

**Comment by sccolbert** [comment]
Notice that there is nothing phosphor-specific in that config. Just treat phosphor like any other package.

**Comment by vrmerlin** [comment]
Thanks for the quick response. Note though that I'm using Angular CLI, which provides a wrapper around WebPack, including the configuration file.  Thus, I don't have a webpack.conf.js file in my project. So, I'm trying to figure out what needs to be in my .angular-cli.json  file. 

(See: https://medium.com/@jeff.boothe/angular-cli-meets-webpack-7c9b1a1e1e89#.ny693bpdn)

I've posted a similar question the Angular CLI team to see if they have any ideas: https://github.com/angular/angular-cli/issues/5084

Has anyone gotten Phosphor to work with CLI?

**Comment by sccolbert** [comment]
I'm surprised it doesn't "just work" out of the box, since the phosphor files should be treated like any other npm module. I'm not familiar at all with Angular or CLI, but unless they just dont allow 3rd party libs at all, I don't see why it would cause any trouble.

**Comment by vrmerlin** [comment]
They definitely support third-party packages; that's why the "styles" and "scripts" sections are in their configuration file. I was surprised too that it didn't work. Hopefully the CLI team can provide an answer. It would be nice if you could provide a search path somehow in their configuration file, not explicitly list each .js file as I seem to need to. I'll keep fiddling...

**Comment by vrmerlin** [comment]
So, it appears that uninstalling 'phosphor' and then installing '@phosphor/widgets', and making some changes for how things moved around, has fixed this problem. Phosphor appears to be loading fine now, although the stylesheets for the docking don't seem to be working right. I'm guessing the stylesheet, that I took from one of your examples, is no longer valid. Is there a newer example around?

**Comment by sccolbert** [comment]
The *required* styles are included with the packages in the `/style` dir. There are currently two: `@phosphor/dragdrop/style/index.css` and `@phosphor/widgets/style/index.css`, unfortunately webpack doesn't yet handle the `style` key in `package.json`, so you'll need to use those full paths: https://github.com/webpack-contrib/css-loader/issues/51

This example dir contains the updated example styles, *which are in addition* to the required CSS above:
https://github.com/phosphorjs/phosphor/tree/master/example/style

Here's where I import the required CSS:
https://github.com/phosphorjs/phosphor/blob/master/example/style/index.css#L8-L9

And here's where I pull in the final stylesheet for the example:
https://github.com/phosphorjs/phosphor/blob/master/example/src/index.ts#L20

And here's how webpack is configured to bundle those styles:
https://github.com/phosphorjs/phosphor/blob/master/example/src/index.ts#L20

**Comment by vrmerlin** [comment]
Great, thanks @sccolbert , that helped.
