### ISSUE TITLE
Commit the dist/ file to the repo

### ISSUE THREAD

**Issue by jasongrout** [phosphorjs/phosphor#21]
Now that the code has settled down more, it would be nice to have the dist/ directory back so that we can check out phosphor and immediately start using it.  Maybe after the shell branch has been merged.

**Comment by sccolbert** [comment]
This is related to adding Phosphor back to bower and npm. This should happen soon.

**Comment by sccolbert** [comment]
Fixed in 2574586d2221992c96d48dc0416c3a19e683fc6e
