### ISSUE TITLE
Signals and Disposables

### ISSUE THREAD

**Issue by akosyakov** [phosphorjs/phosphor#215]
It would be nice if:
- [ISignal.connect](https://github.com/phosphorjs/phosphor/blob/master/%40phosphor/signaling/src/index.ts#L58) returns `Disposable` that does `disconnect` on dispose
- [DisposableSet.add](https://github.com/phosphorjs/phosphor/blob/master/%40phosphor/disposable/src/index.ts#L129) returns `Disposable` that removes an added disposable on dispose

It will allow the following pattern which i think is quite handy:
```ts
const modelListeners = new DisposableSet();
const model2Listeners = new DisposableSet();

set model(model: any) {
  if (this.model !== model) {
    this.modelListeners.dispose();
    this.model = model;
    if (model) {
      this.modelListeners.add(model.onChanged.connect(this.onModelChanged, this));
      this.modelListeners.add(model.onDirtyChanged.connect(this.onDirtyChanged, this));
    }
  }
}

set model2(model: any) {
  if (this.model2 !== model2) {
    this.model2Listeners.dispose();
    this.model2 = model2;
    if (model2) {
      const disposable = model2.onChanged.connect(this.onModel2Changed, this)
      this.model2Listeners.add(disposable);
      this.modelListeners.add(disposable); // also disconnected when model changed
    }
  }
}
```

**Comment by sccolbert** [comment]
It's worth considering, but I'm not sure I like the trade-off of memory allocations to save writing a couple extra lines of code.

What about a static function on `Signal` which disconnected any signals between a given sender *and* receiver. This would be analogous to the existing `Signal.disconnectSender` and `Signal.disconnectReceiver`.  Would have to figure out a name for it.

**Comment by akosyakov** [comment]
So it will be something like:
```ts
set model(model: any) {
  if (this.model !== model) {
    Signal.disconnect(this.model, this);
    this.model = model;
    if (model) {
      model.onChanged.connect(this.onModelChanged, this);
      model.onDirtyChanged.connect(this.onDirtyChanged, this);
    }
  }
}
```
Yes, it will be an improvement already.

**Comment by akosyakov** [comment]
It could be even shorter `model.onChanged` and `model.onDirtyChanged` are functions which connect under the hood:
```ts
model.onChanged(this.onModelChanged, this);
model.onDirtyChanged(this.onDirtyChanged, this);
```

**Comment by sccolbert** [comment]
> So it will be something like:

Yep, something like that.

> It could be even shorter if model.onChanged and model.onDirtyChanged are functions which connect under the hood:

The author of the model class could certainly provide those methods which delegate to an internal signal, but there's no way to automate that in a type-safe fashion.

**Comment by akosyakov** [comment]
In vscode they do it somehow: https://code.visualstudio.com/docs/extensions/patterns-and-principles#_events

**Comment by sccolbert** [comment]
They manually proxy out parts of a private signal-like object to achieve that: https://github.com/Microsoft/vscode/blob/2caf36fdf5ab257e43d29c67e5f0584c9794bf07/src/vs/workbench/api/node/extHostFileSystemEventService.ts#L77

You can do something similar with your own model classes.
