### ISSUE TITLE
Tab extensions

### ISSUE THREAD

**Issue by GordonSmith** [phosphorjs/phosphor#226]
Is it possible to extend a tab with addition "stuff" icons, buttons text etc?

**Comment by sccolbert** [comment]
The `.title` object a `Widget` is used to feed the data for the rendered tabs. A `Title` object has `.className` and `.icon` properties which are used (by default) to add CSS class names to the tab node and tab icon node, respectively. You can use the class names to style the tab how you wish. 
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/title.ts#L123
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/title.ts#L168

If that is not enough, a `TabBar` also accepts an `IRenderer` object which is used to render the tabs themselves. The default renderer can be subclassed for simple customizations. For example, you could use the `setData` api of your `Title` along with a renderer subclass to add info to the node's dataset*, which could then be consumed by CSS for custom styling. Of course, a fully custom renderer is free to change the DOM structure of a Tab entirely:
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/title.ts#L228
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/tabbar.ts#L1277
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/tabbar.ts#L1300

Is that enough flexibility for your use case?

* I should update the default renderer with a method for creating the node dataset just like we have with `CommandPalette` and `Menu` renderers. That will make it easier for subclasses.

**Comment by rmeshksar** [comment]
I managed to add a button to the tab using custom renderer. 
I am wondering what is the best way to handle the click event of the button to be able to handle it on higer level like dock panel.

**Comment by sccolbert** [comment]
You could set an inline click event listener on your button node during rendering. That listener can create a custom bubbling event which it then dispatches immediately. You can then add an event listener to the dock panel's node which traps that custom event.
