### ISSUE TITLE
Tabbar extensions

### ISSUE THREAD

**Issue by GordonSmith** [phosphorjs/phosphor#227]
Ability to add extra "stuff" to the tab bar ("close all", "drop list of tabs" comes to mind).

**Comment by sccolbert** [comment]
If this is in context of a `DockPanel`. That widget accepts an `IRenderer` option, which is used to create the `TabBar` widgets used by the panel. You can create your own renderer which produces your custom `TabBar` instance:
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/docklayout.ts#L960
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/dockpanel.ts#L771

You are free to add more dom nodes to the `.node` of a `TabBar`, as long as you don't mess directly with its `.contentNode`: https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/tabbar.ts#L294

Is that enough flexibility for your use case?
