### ISSUE TITLE
Get dragged widget in DockPanel dragenter?

### ISSUE THREAD

**Issue by jjrv** [phosphorjs/phosphor#229]
My floating dialog area needs the dragged widget's size to draw an appropriate overlay, so it calls the factory function from `event.mimeData.getData('application/vnd.phosphor.widget-factory')` on `p-dragenter`. This has the side effect that `event.dropAction` can be set to `none` earlier and dragging forbidden things, like a parent widget, immediately shows a `no-drop` cursor. This seems better than silently ignoring the drop like the DockPanel does.

Could the DockPanel similarly indicate invalid drags? Is calling the factory from `mimeData` a bad idea when not actually intending to create a new widget yet and if so, could there be another API to peek at the dragged widget if it's already instantiated?

**Comment by sccolbert** [comment]
If you're doing such a custom drag, just add a new mimetype to the `MimeData` object, which is *not* a factory, but an actual widget, something like `application/vnd.jjrv.phosphor-widget`, and use that if present instead of the default mimetype.

**Comment by sccolbert** [comment]
you could also simply add the widget's size to the mimedata and use it if present to draw the overlay.

**Comment by jjrv** [comment]
The widgets are usually dragged to/from a DockPanel, so it sets and parses the `MimeData`.

**Comment by sccolbert** [comment]
Wouldn't this be fixed by what we were talking about earlier with sending a message to the widget which is about to be dragged so that it can add extra stuff to the mimedata?

**Comment by jjrv** [comment]
That would require handling such a message in all the child widgets, or adding a hook to them? I'd like to have a single handler somewhere that gets notified when a drag is about to start, with info about the widget to be dragged. If it could also cancel the drag, that could fix #223 as well.

**Comment by jjrv** [comment]
Currently the ugliest part of my code is the mixin I pasted [here](https://github.com/phosphorjs/phosphor/pull/196#issuecomment-281629317) that prevents the DockPanel from monopolizing drag events, but still allows it to see them when not handled by child widgets. Basically that means the DockPanel must let `p-dragenter` events through without calling `stopPropagation` while its children must catch them, so both the DockPanel and its children can still then see other drag events.

**Comment by sccolbert** [comment]
You could install a message hook on any widget you care about being handled in a special way.

I'm trying to be flexible here, but I'm not interested in making changes solely to support floating mdi style windows. So if more generic solutions don't work for your case, you'll need to write your version of `DockPanel` which reuses the `DockLayout` class.

**Comment by jjrv** [comment]
As I said, a hook on starting a drag would also fix #223 so it's not specific to my case.

**Comment by sccolbert** [comment]
#223 is something different. That's talking about disabling any changes to the dock panel to make it more like a dashboard.

**Comment by jjrv** [comment]
But if the DockPanel calls something when starting a drag and passes it the widget and the drag object, presumably the drag object could be disposed when that widget shouldn't be dragged, so it would allow disabling changes to certain widgets.

**Comment by sccolbert** [comment]
It wouldn't prevent the reordering of tabs, so it's not the right solution for #223

**Comment by jjrv** [comment]
The `FloatArea` is released and works OK so closing this.
