### ISSUE TITLE
DockPanel: doesn't stretch when attached to a DIV

### ISSUE THREAD

**Issue by romainbar** [phosphorjs/phosphor#258]
Updating the example-dockpanel demo to attach 'bar' and 'main' to a DIV instead of document.body, the DockPanel doesn't stretch to the whole DIV (which is occupying the whole screen with 'width:100%;height:100%') as it does with the body.

Is the DockPanel designed to be attached to document.body only?

Sample code:
  ngAfterContentInit()
  {
    Widget.attach(this.bar, this.parentDiv.nativeElement);
    Widget.attach(this.main, this.parentDiv.nativeElement);
  }

**Comment by sccolbert** [comment]
Can you post all of your code. Specifically, are you calling `.update()` on the panel when the window resizes? You only have to call `.update()` on your root panel, it will take care of the rest:

https://github.com/phosphorjs/phosphor/blob/master/examples/example-dockpanel/src/index.ts#L361

**Comment by sccolbert** [comment]
To answer your second question. A phosphor widget can be used anywhere, you just have to set up your CSS correctly, and notify the root widget when it's likely to have been resized.
