### ISSUE TITLE
Browser compatibility? Especially IE 10

### ISSUE THREAD

**Issue by romainbar** [phosphorjs/phosphor#259]
I couldn't find any documentation on the browser compatibility.
I'm wondering whether IE 10 is supported. IE 11 works out of the box.

Running the demos from http://phosphorjs.github.io/examples.html in IE 10 always yields SCRIPT5009: 'WeakMap' is undefined.

Building the DockPanel demo myself (from examples/example-dockpanel) yields a different error:
TypeError: Unable to set property 'mode' of undefined or null reference
  at DockPanel (eval code:50:9)
  ...

upon line:
 let dock = new DockPanel();

**Comment by sccolbert** [comment]
We support IE 11 and the most recent stable versions of Chrome, FF, and Edge. 

We do not support IE 10.
