### ISSUE TITLE
The doc links are broken

### ISSUE THREAD

**Issue by scharf** [phosphorjs/phosphor#265]
The links  on http://phosphorjs.github.io/phosphor/docs.html are broken (404). For example: http://phosphorjs.github.io/phosphor/api/widgets/globals.html

**Comment by sccolbert** [comment]
Duplicate of #203

**Comment by sccolbert** [comment]
Thanks for the report! We hope to have this fixed soon.

**Comment by sccolbert** [comment]
Fixed in #266.
