### ISSUE TITLE
Phosphor docking seems to make UI really slow

### ISSUE THREAD

**Issue by vrmerlin** [phosphorjs/phosphor#273]
We are noticing a significant decrease in UI performance, that appears to be related to Phosphor (and/or Angular2 or PrimeNG, which we are also using). We are using   "@phosphor/widgets", version 1.2.0.

When we bring up a window with a PrimeNG tree and a few other things, placed in a Phosphor docking frame, it's nice and snappy and appears to work well. If we open up a second frame, even one whose content is hidden as a tab, suddenly the content of the first frame gets noticeably slow. The action we are doing is really simple -- simply clicking on the nodes of the tree to highlight them. There is a half second lag on each click.

As anyone else observing this behavior? I've tried profiling with the browser debuggers, but it's not clear where the problem is. It appears to be taking a long time to do repaints.

John

**Comment by sccolbert** [comment]
What do you mean by "second frame"? What browser/OS?

Can you provide a reproducible example?

**Comment by sccolbert** [comment]
I'd be surprised if this is a problem with Phosphor.

**Comment by sccolbert** [comment]
If you email me (or host) a simple app, I can take a look for you.

**Comment by vrmerlin** [comment]
I should have said "panel", not "frame" I guess.   I'll see if we can isolate the behavior into an example that I can give you. This problem happens on Windows and Linux, Chrome or Firefox or Edge.

**Comment by vrmerlin** [comment]
after a lot of further debugging, it appears that Phosphor exasperates the problem because we have more "stuff" on the screen, but that the root problem is with the PrimeNG components, or the way we are using them. So, we'll focus on that and not on Phosphor for now.

**Comment by sccolbert** [comment]
As an FYI a Phosphor Widget will get show/hide messages when it is made visible/hidden on the screen. If you can disable your PrimeNG "logic" when the widget is not visible, that may help you how.

Your widget subclass can reimplement any of:
`onBeforeShow`
`onAfterShow`
`onBeforeHide`
`onAfterHide`

**Comment by sccolbert** [comment]
You can also test whether a widget is visible on the screen via `widget.isVisible`
