### ISSUE TITLE
tsconfig:  UMD Module

### ISSUE THREAD

**Issue by GordonSmith** [phosphorjs/phosphor#276]
Rather than only targeting commonjs, switching to UMD would open the door for folks who use AMD loaders and related build tools.

**Comment by GordonSmith** [comment]
Also adding es6/module/jsnext support would be pro-active.

**Comment by GordonSmith** [comment]
This whole topic is something I struggle with.  What is the "expected" deliverables from a JS library these day (not just phosphor but in general)?
* lib/index.js (umd sources for the commonjs / amd folks - all sources in separate files)
* lib-es6/index.js (for the future proofing folks - all sources in separate files)
* dist/pkg.js (umd package exporting the lib functions, but including dependencies as private)?
* dist-es6/pkg.js (es6 package exporting the lib functions, but including dependencies as private)?

**Comment by jasongrout** [comment]
One thought is that things like webpack or other bundlers can bundle a phosphor commonjs dependency plus your other code and wrap it all in a umd bundle, if you wish. Settling on distributing a commonjs node module allows the package to be understood by a wide variety of bundlers and used in a wide variety of contexts.

**Comment by GordonSmith** [comment]
I thought UMD wouldn't affect that (since it still supports the commonjs require syntax)?  
Plus this wouldn't have to be a either or scenario, it could support both.

**Comment by sccolbert** [comment]
Choosing a single module format and letting build tools adapt as needed, simplifies things for us as a project. The goal is to eventually remove commonjs altogether once the runtimes support native ES6 imports.

**Comment by sccolbert** [comment]
The other thing is that Phosphor is intended to be used from a node-based build system, and is distributed as an npm package. Node uses commonjs, hence we use commonjs.
