### ISSUE TITLE
Dock Panel SaveLayout with custom Widgets serialization

### ISSUE THREAD

**Issue by rmeshksar** [phosphorjs/phosphor#280]
Hi,
Imagine that in a portal like application, there are predefined set of the widgets and users can add them to a dock panel and re-organize the panes.
Now, user can save the layout and load them later.
saveLayout method of the dock panel, also adds widgets object (can be very big) to the generated object, but in our case we only need the Id of the predefined widget to save it in the database, then when loading the dashboard, the dock panel layout is restored and then widgets are getting added by our code.

Is there any solution to this use case?

**Comment by sccolbert** [comment]
JupyterLab does exactly this. It converts the object it gets from `saveLayout()` into a JSON object containing the widget `id`s. It the restores that object on restart by converting its JSON structure back into a layout, swapping the `id`s for the rehydrated widgets.

In short, you don't need anything from Phosphor to do this, you can do it yourself with a small translation function that you write. 

It wouldn't be good for Phosphor to assume the widget `id` is the only way to serialize the widget, and it would also need to invent the deserialization step (which would be even worse), so it leaves that part up to the user.

**Comment by yerfdogyrag** [comment]
Just in case anyone else is looking, the code in jupyterlab can be found here as of 7/2017

https://github.com/jupyterlab/jupyterlab/blob/master/packages/application/src/layoutrestorer.ts
