### ISSUE TITLE
how do we make a widget active and visible in DockPanel?

### ISSUE THREAD

**Issue by vrmerlin** [phosphorjs/phosphor#291]
We use the addWidget() call to add a widget to our panel (generated by a menu selection). The widget shows up in the tab list at the end, and the user must select the tab to make it visible and use it. Is there a way to make it visible automatically?  I tried widget.activate() and widget.show() and neither one worked.

Thanks,
John

**Comment by sccolbert** [comment]
You can use either `myDockPanel.selectWidget(...)` or `myDockPanel.activateWidget(...)`:
https://github.com/phosphorjs/phosphor/blob/06f24b7429e79da108e909f4aa1ba40661fe9372/packages/widgets/src/dockpanel.ts#L245-L279
