### ISSUE TITLE
resizing misbehavior

### ISSUE THREAD

**Issue by vrmerlin** [phosphorjs/phosphor#293]
We are using PrimeNG with DockPanel, and have a layout similar to this:

https://www.primefaces.org/poseidon-ng/#/

Except, where their dashboard content is, we have a DockPanel. The menu on the left fires up new windows in the DockPanel. In general, it's working quite well, except we have a misbehavior we can't figure out related to resizing. We've got this code:

` window.onresize = () => { console.info("Fitting!");  GuiDockerComponent.dockPanel.update(); };`

And, when we resize the browser window, indeed the DockPanel behaves great -- resizes proportionally as expected.  The problem comes when we click the "<" symbol in the upper left hand corner, which collapses the menus. In the PrimeNG example, the layout of the dashboard behaves gracefully, and redistributes the content as expected. In our code, the DockPanel simply shifts to the left, leaving "white space" on the right hand side. The DockPanel does not resize itself into the new area until we then resize the browser window manually.

We have a code segment associated with the menu to manually trigger the resize:

`window.dispatchEvent(new Event('resize'));`

I can see the "Fitting!" text echoed to the screen, so I know the event is firing, but the DockerPanel doesn't resize correctly. It's like its firing before the menu is collapsed, not after. Any idea what might be going wrong? We are "so" close to getting these pieces/parts working!

**Comment by sccolbert** [comment]
You have to call ` GuiDockerComponent.dockPanel.update();` *whenever it's size may have changed*.

If the whole app is built with Phosphor, the framework handles it automatically since it knows when it resizes its children (for the most part). In this case, the dock panel doesn't know it's been resized when you collapse the menus (because it has no way of knowing) so it doesn't relayout it's children. You have to tell it when it's been resized.

**Comment by sccolbert** [comment]
Since the menu collapse is animated, set a timer to call `update()` after the animation is finished.

**Comment by sccolbert** [comment]
If you wanted to achieve the same animated effect, call `update()` in a `requestAnimationFrame` loop until the menu collapse is finished.

**Comment by vrmerlin** [comment]
Ok, thanks. I'll have to talk to PrimeNG, about how we can inject code into their animation.

**Comment by sccolbert** [comment]
If you know approximately how the long the animation is, you dont need to. When you click the menu, just start an animation frame loop for that duration.

Something like this pseudocode:

```
function rafLoop(duration: number, widget: Widget): void {
  let t1 = Date.now();
  requestAnimationFrame(doit);
  function doit() {
    let t2 = Date.now();
    if (t2 - t1 >= duration) {
      return;
    }
    widget.update();
    requestAnimationFrame(doit);
  }
}

menuThingy.onClick = () => { rafLoop(500, myDockPanel); };
```

**Comment by vrmerlin** [comment]
Holy cow, you're good. :-) That worked, without even a change to your "pseudocode". Thank you!
