### ISSUE TITLE
css for Dockpanel and iframe

### ISSUE THREAD

**Issue by yerfdogyrag** [phosphorjs/phosphor#305]
@sccolbert , I remember you mentioning that there needs to be some special CSS when using the dockpanel and an iframe in order to prevent the frame from stealing the drag events.  Do you happen to have a pointer to that?  I found some references in jupyterlab, but couldn't quite figure out where it happened.

Thanks!

**Comment by sccolbert** [comment]
https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/style/iframe.css#L17-L35

replace `body.p-mod-override-cursor .jp-IFrame` with a selector which targets your desired iframes. You can use `body.p-mod-override-cursor iframe` to target *all* iframes on the page.

**Comment by sccolbert** [comment]
Let me know if you need more info.

**Comment by yerfdogyrag** [comment]
Thanks!  I'll give it a go.
