### ISSUE TITLE
SplitPanel +min-width css

### ISSUE THREAD

**Issue by GordonSmith** [phosphorjs/phosphor#306]
I have the following CSS:
```
.p-Widget.p-SplitPanel-child.legend {
    min-width: 20%;
    max-width: 50%;
}
```

Rather than limiting the sizing to a % - it seems to restrict it to 20px->50px

**Comment by sccolbert** [comment]
Absolute layouts assume min/max sizes are expressed in `px`.

**Comment by GordonSmith** [comment]
Can I override it programmatically on a resize event of such like?

**Comment by sccolbert** [comment]
Sure. If you change the `min/max` size of `widget` programmatically, just call `widget.parent.fit()` when you're done so that the parent can relayout the children.

I wouldn't do it on a resize event though, since that may cause a recursive resize. Best to do it in a collapsed, infrequent fashion, since `fits()` are relatively much more expensive than regular resizes.

Maybe there is a better way to achieve your goal? What is your goal?

**Comment by GordonSmith** [comment]
I want to restrict the RHS of a two panel horizontal split pane to:
min: 240px
max:  33%

**Comment by sccolbert** [comment]
Yeah, doing that "correctly" would require me to update the box layout engine to understand percent sizes. I would say just pick a reasonable max size in pixels, and see how far you can get with that.

**Comment by GordonSmith** [comment]
Related question - is there a clean way to have a "fixed" panel (think a Title) - the look I am going for:
```
+======================+
|                      |
+======================+
|                |     |
|                |     |
|                |     |
|                |     |
|                |     |
|                |     |
+======================+
```

**Comment by sccolbert** [comment]
```
+======================+
|          A           |
+======================+
|                |     |
|                |     |
|         B      |  C  |
|                |     |
|                |     |
|                |     |
+======================+
```
``` typescript
let A = new Widget();  // { min-height: <whatever>px; } 
let B = new Widget();
let C = new Widget();

let outer = new BoxPanel({ direction: 'top-to-bottom' });
let inner = new SplitPanel({ orientation: 'horizontal' });

BoxPanel.setStretch(A, 0);
BoxPanel.setStretch(inner, 1);

inner.addWidget(B)
inner.addWidget(C);

outer.addWidget(A);
outer.addWidget(inner);
```

**Comment by GordonSmith** [comment]
That helps - thx.
