### ISSUE TITLE
DockPanel:  Unable to override "_renderer" in derived class

### ISSUE THREAD

**Issue by GordonSmith** [phosphorjs/phosphor#310]
This is just a syntactical annoyance, but I am trying to initialize a DockPanel with a Custom Renderer via a derived class and am unable to do it cleanly without the use of a factory:

As an example a DockPanel with the ability to enable/disable dragging of tabs:

```typescript
export class PRenderer extends DockPanel.Renderer {
    _owner: PDockPanel;  //  Should be private

    constructor(owner?: PDockPanel) {   //  Should not be optional
        super();
        this._owner = owner;
    }

    createTabBar(): TabBar<Widget> {
        const bar = super.createTabBar();
        bar.tabsMovable = this._owner.tabsMovable;
        return bar;
    }
}

export class PDockPanel extends DockPanel {
    private _tabsMovable: boolean = true;
    get tabsMovable(): boolean {
        return this._tabsMovable;
    }
    set tabsMovable(value: boolean) {
        this._tabsMovable = value;
        each(this.tabBars(), tabbar => tabbar.tabsMovable = value);
    }

    constructor(options: DockPanel.IOptions = {}) {
        super({
            ...options,
            renderer: options.renderer || new Renderer(this)  //  <---  Syntax Error...
        });
    }

    static createPDockPanel(options: DockPanel.IOptions = {}) {
        //  This works, but would be preferable to be able to do it in the constructor.
        const renderer = new PRenderer();
        const retVal = new PDockPanel({ renderer });
        renderer._owner = retVal;
        return retVal;
    }
}
```

**Comment by sccolbert** [comment]
Here's how I would do what I think you're trying to do.

```ts
export class PDockPanel extends DockPanel {
    constructor(options: DockPanel.IOptions = {}) {
        let baseRenderer = options.renderer || DockPanel.defaultRenderer;
        let renderer: DockPanel.IRenderer = {
            createTabBar: () => {
                let tabBar = baseRenderer.createTabBar();
                tabBar.tabsMovable = this._tabsMovable;
                return tabBar;
            },
            createHandle: () => {
                return baseRenderer.createHandle();
            },
        };
        super({ ...options, renderer });
    }

    get tabsMovable(): boolean {
        return this._tabsMovable;
    }

    set tabsMovable(value: boolean) {
        if (this._tabsMovable === value) {
            return;
        }
        this._tabsMovable = value;
        each(this.tabBars(), tabbar => { tabbar.tabsMovable = value });
    }

    private _tabsMovable = true;
}
```

**Comment by GordonSmith** [comment]
That is pretty much what I tried first, but that produces the following error:  ```A 'super' call must be the first statement in the constructor when a class contains initialized properties or has parameter properties.``` this is with TS 2.5.2.

I am not sure what your philosophy is on public, protected and private members and I was trying to avoid getting into the whole "can you make this protected instead of private" debate, but I think I am snookered here unless _renderer is made protected?

FWIW my rule of thumb is to default all members to protected unless there is a very good reason to make them either private or public.

**Comment by sccolbert** [comment]
I typed my example without trying it. I'll update with a working one when
I'm back at my computer. I try to avoid using protected properties whenever
possible.

**Comment by sccolbert** [comment]
Related typescript discussion:
https://github.com/Microsoft/TypeScript/issues/8277

**Comment by sccolbert** [comment]
Before I go figuring out a way around this, is this the *only* reason you are creating a custom renderer? Because if so, it still might not help you. Internally the dock panel base class creates its own custom renderer, which always sets `tabsMovable` to `true`. So even if we work around the type system, the base class is still going to block you. 
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/dockpanel.ts#L828

What's the use case for a dock panel that doesn't support interactive docking? (tabs must be movable for interactive docking).

**Comment by GordonSmith** [comment]
Some thoughts on that:
1.  IMO Those "static" settings should really be in the default render class instance.
2.  When possible, they should be passed in to the TabBar constructor as a default option and not set after construction (it would simplify the case when you have different TabBar implementations),

To answer your question, I want the ability to "lock/unlock" the current layout at runtime, without recreating the page and moving the widgets into other containers.  I am able to globally lock/unlock (via the "toolbars" method), but am unable to cleanly open it initially "locked".

Next I am hoping to add the ability to optionally show/hide the tabbar on a per "cell/panel" basis.

IMO if your goal is to create an extensible Class Library, then its not appropriate to be defaulting internal members to "private" without good considered reason.  Otherwise it just ends up being a frustrating experience for anyone who wants to extend your classes.  Of course if your goal is to develop a rock solid package for reuse (and not abuse) the previous statement doesn't apply.
