### ISSUE TITLE
[Question] How to update `input.value` with vdom?

### ISSUE THREAD

**Issue by svenefftinge** [phosphorjs/phosphor#313]
I'm using a vdom based form with an input field on which I want to reset the value.
Unfortunately, it doesn't work since `input.setAttribute('input', newValue)` will not update the actual value but only the default one. 
How should I solve this? Obtaining the real element and setting the value?

**Comment by svenefftinge** [comment]
Maybe a special attribute for such browser managed state would be good?

**Comment by blink1073** [comment]
Hi @svenefftinge, the way we have been handling this is to use the created element directly, for example in the [menu](https://github.com/phosphorjs/phosphor/blob/23b9d075ebc5b73ab148b6ebfc20af97f85714c4/packages/widgets/src/menu.ts#L690).  In light of the React [re-license](https://code.facebook.com/posts/300798627056246), we are considering moving to using React as a dependency and deprecating the Phosphor virtual dom, cf https://github.com/phosphorjs/phosphor/issues/302.

**Comment by svenefftinge** [comment]
Ok, thanks. I did that, too.
