### ISSUE TITLE
Make handler methods of `DockPanel` protected

### ISSUE THREAD

**Issue by akosyakov** [phosphorjs/phosphor#315]
I want to subclass and customize handler of DockPanel, particularly:
https://github.com/phosphorjs/phosphor/blob/51d5c7bc48ba6789a4f15aa3942aed070938c4bd/packages/widgets/src/dockpanel.ts#L894-L896

**Comment by sccolbert** [comment]
Instead if changing the dock panel, re-implement `onCloseRequest` in your widget, or if you can't do that (because you don't own the widget class) use a message hook to intercept `close-request` on those widgets.

**Comment by akosyakov** [comment]
Sounds good
