### ISSUE TITLE
Examples in documentation

### ISSUE THREAD

**Issue by stoplion** [phosphorjs/phosphor#324]
I have some example pages bookmarked from the old website. For instance: 
http://phosphorjs.github.io/examples/dockpanel/ 
Unless I'm missing something, it appears the main website does not link to these examples any longer? Are these "example pages" still relevant and up to date? If so, can these examples be linked (again, maybe they are but I'm not seeing it) to the main page?

**Comment by sccolbert** [comment]
The examples were written for the pre-1.0 versions of the Phosphor packages, and were thus out of date. When I have the time, I'll update them for the 1.0 releases.
