### ISSUE TITLE
Chrome 64 supports element resize DOM events

### ISSUE THREAD

**Issue by jasongrout** [phosphorjs/phosphor#327]
FYI. See https://www.chromestatus.com/feature/5705346022637568.

**Comment by jasongrout** [comment]
(This is just an FYI issue. Feel free to close when noted :).

**Comment by sccolbert** [comment]
Noted. Thanks. Will be great when broadly supported.

**Comment by jasongrout** [comment]
Just FYI, there's also support in the pipeline for Chrome 65 for some of the CSS Paint API: https://developers.google.com/web/updates/2018/01/paintapi

(see also https://ishoudinireadyyet.com/ for more progress...)
