### ISSUE TITLE
[question] Asynchronous widget factory for the DockPanel

### ISSUE THREAD

**Issue by kittaakos** [phosphorjs/phosphor#330]
Is there a way to have `async` widget factory for the `DockPanel`? Currently, the [widget factory](https://github.com/phosphorjs/phosphor/blob/4d787b32136861adae4ebadc6c877a130d0cb216/packages/widgets/src/dockpanel.ts#L535) expected to be synchronous. I would like to achieve something like this. Is it possible? Thank you!

```typescript
const mimeData = new MimeData();
const factory: () => Promise<Widget> = () => Promise.resolve(new Widget());
mimeData.setData('application/vnd.phosphor.widget-factory', factory);
const drag = new Drag({
  mimeData,
  proposedAction: 'move',
  supportedActions: 'move'
});
// ...
drag.start(clientX, clientY).then(() => {
  // ...
});
```

**Comment by sccolbert** [comment]
Hi there. That's not currently possible, and I'm not sure I want to support it. It would require the DockPanel to violate some of its invariant assumptions about the internal layout. 

What we do in JupyterLab is to use a parent widget which can be instantiated synchronously, but which asynchronously loads its own child content. This allows us to show a "loading" spinner graphic as the initial content, and swap that out with the actual child content once it's ready. This has the advantage of being instantaneous feedback to the user, while given the child as long as it needs to load.

**Comment by kittaakos** [comment]
Thanks for the hint, I'll give it a try.
