### ISSUE TITLE
Menu entry from command uses both icon + label

### ISSUE THREAD

**Issue by vidartf** [phosphorjs/phosphor#331]
Adding a command with both a field `iconClass` and `iconLabel`, and making a menu entry for it (command entry), causes the label and icon to be rendered on top of each other:

![image](https://user-images.githubusercontent.com/510760/39256699-dda0acb6-48af-11e8-8613-1e38632de127.png)

The icon class is styled with `background-image: url(../some image path...);`.

While I cannot see that `iconClass` and `iconLabel` are fully documented, I would expect that the label would serve a more secondary role to the icon (alt text, tooltip, or similar). Is there a way to achieve this? What is the intended way to use/combine these fields?

**Comment by sccolbert** [comment]
Hmm. I think that when I designed this I was thinking that one or the other (icon or label) would be used, or that the label would be displayed below the icon in a toolbar button. It might be reasonable to display the icon label as a tooltip for a menu.

**Comment by sccolbert** [comment]
Here are the docs for those properties:
https://github.com/phosphorjs/phosphor/blob/master/packages/commands/src/index.ts#L647-L675

It's up to a view to decide how to render the options.

**Comment by sccolbert** [comment]
and here's where the default renderer renders the menu item icon:
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/menu.ts#L1163-L1166

**Comment by vidartf** [comment]
I think I understand. Then renderers that only use an icon can e.g. put the `label` field (not `iconLabel`) as tooltip (title attribute) of the node, while menus that already have the label shown don't need the tooltip. Thanks!

**Comment by sccolbert** [comment]
I don't think this should be closed. We should definitely figure out the right way for the menu to treat the icon label.

**Comment by vidartf** [comment]
I think having the icon label as it is makes sense. Then you can use unicode characters as the icon (💩), and still have a class for it.

**Comment by sccolbert** [comment]
That's a good point.

**Comment by vidartf** [comment]
My solution was just to remove the `iconLabel` field (I forgot that jupyterlab notebook toolbar uses the label as the tooltip), but yes, that could be a fallback if I couldn't do that. I originally added the `iconLabel` field in an effort to be as exhaustive as possible in the command data.

Maybe a decent solution would be to add something like this to the `iconLabel` docstring: "Useful for when you want to add text content to the icon in addition to, or instead of, an image." Or maybe having this issue in the repo is enough.
