### ISSUE TITLE
Firefox 60 specifically discourages using `keyCode`

### ISSUE THREAD

**Issue by jasongrout** [phosphorjs/phosphor#336]
Phosphor uses the `keyCode` for keyboard shortcuts and to detect key events, like: https://github.com/phosphorjs/phosphor/blob/c3382248e0bf05a2ab2ff2aeb71ce96fb8381770/packages/keyboard/src/index.ts#L143

I just noticed in the [FF 60 release notes](https://developer.mozilla.org/en-US/Firefox/Releases/60#Changes_for_web_developers), there is a note: 

> The KeyboardEvent.keyCode attribute of punctuation key becomes non-zero even if the active keyboard layout doesn't produce ASCII characters. See [these notes](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#keyCode_of_punctuation_keys_on_some_keyboard_layout) for more detail. Please do not use KeyboardEvent.keyCode in new applications — use KeyboardEvent.key or KeyboardEvent.code instead.

I glanced at it and it doesn't seem like it affects us, but thought I'd open an issue to investigate later more deeply.

**Comment by sccolbert** [comment]
It's been deprecated for years, but until all browsers converge on
something else which is actually implemented correctly, it's the best we
have to make something which actually works.

**Comment by jasongrout** [comment]
That's what I figured. Still, thought it would be good to flag a change in FF 60 behavior.

However, as far as I can tell in a quick glance, it doesn't actually affect us, since we are assuming people are going to hand-code keyboard layouts if they aren't using the default standard US layout. I'll close this, since it's been duly noted.

**Comment by jasongrout** [comment]
FYI, here is a Firefox bug tracking more changes to `keyCode` behavior that hasn't shipped yet, but is tentatively scheduled for Firefox 66: https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1496288 (see also https://bugzilla.mozilla.org/show_bug.cgi?id=1520756).

> (TENTATIVE, MIGHT NOT HIT 66) From 66 onwards, when the KeyboardEvent.keyCode property of the keypress event object is 0, the value will be the same as KeyboardEvent.charCode. Conversely, when charCode is 0, it will be the same as keyCode. This mirroring behavior matches other browsers and is expected to solve most associated compatibility issues, however user agent sniffing might cause further issues in some JavaScript libraries. Note that in spec terms, we've switched from the split model to the conflated model (see How to determine keyCode for keypress events in the UI Event spec).
