### ISSUE TITLE
Investigate a constraint-based layout manager based on Kiwi.

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor#35]

**Comment by mladen107** [comment]
Hello,
I used this algorythm https://github.com/slightlyoff/cassowary.js/ in past for solving constraits on layout.

**Comment by sccolbert** [comment]
@mladen107 Thanks. Kiwi is an implementation of Cassowary I made a few years ago, which is faster than the original: https://github.com/nucleic/kiwi

**Comment by sccolbert** [comment]
Closing this a stale. A need for this hasn't really arisen.
