### ISSUE TITLE
Phopshor JS + bokeh  EXAMPLE

### ISSUE THREAD

**Issue by davidpasquale** [phosphorjs/phosphor#366]
Hi, 
thank you for the amazing job!
I would like to perform a web app based on bokeh and phosphor.
Is it possible for you to update this old example?

[https://github.com/dwillmer/phosphor-bokeh-demo/](url)

I am not able to get it working.
Thank you very much for your help!

**Comment by sccolbert** [comment]
Sorry. I'm not the author of that example.
