### ISSUE TITLE
Rendering issue with TabPanel in React component: height is always 0

### ISSUE THREAD

**Issue by ssurana** [phosphorjs/phosphor#379]
I am trying to use TabPanel in a react component, and running into an issue with rendering. The TabPanel renders with height 0. Following is an exampler: https://codesandbox.io/s/8k16o2z662

@tracksaw

**Comment by sccolbert** [comment]
The CSS provided by Phosphor is *necessary but insufficient* for a properly functioning app. You need your own theme which specifies (among many other things) the tab bar min-height. Try including the [default-theme](https://github.com/phosphorjs/phosphor/tree/master/packages/default-theme) CSS and see if that fixes your problem.

**Comment by ssurana** [comment]
@sccolbert Thank you!!
