### ISSUE TITLE
consider to use web-components (custom elements) for all phospor elements

### ISSUE THREAD

**Issue by nimo23** [phosphorjs/phosphor#382]
Please use web-components (custom-elements) for all phospor elements. For example,

The use of http://phosphorjs.github.io/examples/dockpanel/ can be simplified by

```
<phospor-dockpanel prop=""...>
...
<phospor-dockpanel ...>
```
More information: https://lit-element.polymer-project.org/ or https://stenciljs.com/

web-components  are native and very fast in compare to vdom (for example, react).

**Comment by sccolbert** [comment]
Web components are not (yet) standardized. If and when that happens, we can discuss the ramifications.
