### ISSUE TITLE
Is Server-side rendering with phosphor possible ?

### ISSUE THREAD

**Issue by firecrackerz** [phosphorjs/phosphor#384]

**Comment by sccolbert** [comment]
Phosphor is not really designed for that, but I also haven't thought about too much. I guess I never really saw the need. What use-case are you trying to fulfill with server-side rendering?

**Comment by firecrackerz** [comment]
I'm currently using Monaco Editor + phosphor + monaco-languageclient (which uses WebSockets to talk to the server application),
so I was thinking of SSR possibilities.

**Comment by sccolbert** [comment]
What's SSR?

**Comment by jasongrout** [comment]
> SSR

In this context, server-side rendering?

**Comment by sccolbert** [comment]
Duh. In my defense, the coffee hadn't kicked in yet.

**Comment by sccolbert** [comment]
However, I'm still not clear on the use case here. What exactly are you wanting to render server-side, and why?
