### ISSUE TITLE
npm package dependency is broken

### ISSUE THREAD

**Issue by qzchenwl** [phosphorjs/phosphor#386]
`@phosphor/widgets@1.7.0` depends on `@phosphor/disposable@^1.1.3` which is not found in npmjs.com.

This would cause installing a jupyter related package to raise an error like `No matching version found for @phosphor/disposable@^1.1.3`

**Comment by blink1073** [comment]
Thanks for the report!  Npm had logged me out during publish. I had thought I could manually publish just the one package. I'll push them all when I get back to my machine.

**Comment by blink1073** [comment]
I'll follow up with an upgrade to lerna and separate the versioning and publish steps.

**Comment by blink1073** [comment]
All set!  I'll leave this open until I upgrade lerna.

```
$ npm install @phosphor/widgets
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN temp@1.0.0 No description
npm WARN temp@1.0.0 No repository field.

+ @phosphor/widgets@1.7.0
added 13 packages from 4 contributors and audited 29 packages in 4.613s
found 0 vulnerabilities
```
