### ISSUE TITLE
focus tracking does not track widgets with nested iframe properly

### ISSUE THREAD

**Issue by akosyakov** [phosphorjs/phosphor#394]
If a widget node contains iframe. When iframe gets focused then `blur` event is fired for a node, not `focus`, so a widget is not tracked anymore as active although its content is focused.

**Comment by sccolbert** [comment]
iframes generally break everything with regard to focus and mouse events. I'm not sure supporting them is worth the effort.

**Comment by akosyakov** [comment]
@sccolbert we can fix it on our side by installing focus/blur event listeners inside iframe, don't think it can be fixed generally
