### ISSUE TITLE
distributing as es6

### ISSUE THREAD

**Issue by akosyakov** [phosphorjs/phosphor#413]
For Theia we would like to move to es6 target. Would It be possible to distribute phosphorjs transpiled to es6 in addition to es5, e.g. under another npm tag?

**Comment by blink1073** [comment]
I think we could do this as part of the 2.0 effort, but I think it is too much of a maintenance burden to do before then.

**Comment by akosyakov** [comment]
@blink1073 sounds good, we can republish from our fork for time being
