### ISSUE TITLE
Applying zoom to parent of some phosphor widgets breaks mouse targeting

### ISSUE THREAD

**Issue by aschlaep** [phosphorjs/phosphor#423]
I first found this in jupyterlab, but to reproduce with just phosphor widgets, apply `zoom: 70%` or similar to the body in this example: http://phosphorjs.github.io/examples/menus/

Next, try hovering and clicking on the menu bar or the tabs.  The widgets seem to think that the mouse is to the left of where it actually is (when applying zoom >100%, to the right) for the hover and click effects.

**Comment by sccolbert** [comment]
Do all browsers exhibit the same behavior?

**Comment by aschlaep** [comment]
I originally tested it in Chrome, the behavior is very similar in Safari, the hover and click targeting in Edge seems to work with `zoom`, but in the menus example I linked above, the menu placement overlaps the menubar a bit.  Firefox does not support the `zoom` property.

**Comment by sccolbert** [comment]
> Firefox does not support the zoom property.

Maybe I'm thinking about something different. If I `ctrl` + `wheel` in FF, it will zoom. Are you talking about something different?

**Comment by sccolbert** [comment]
Are you talking about the non-standard `zoom` CSS property?
https://css-tricks.com/almanac/properties/z/zoom/

If that's what you are talking about, we don't support that. It's non-standard.

**Comment by aschlaep** [comment]
Yes, that's what I was talking about.  Didn't realize it was non-standard, sorry!  Closing.
