### ISSUE TITLE
Enable setting context menu icon

### ISSUE THREAD

**Issue by btheeten** [phosphorjs/phosphor#428]
It seems the phosphorjs context menus include an icon, which (according to the code) needs to be set through an iconClass. However setting this iconClass doesn't seem to be exposed through the IItemOptions interface.

**Comment by sccolbert** [comment]
The content for a menu is provided by the underlying command. You add the `iconClass` when you register the command in the `CommandRegistry`.

**Comment by btheeten** [comment]
Thank you very much for the quick answer. That solves my problem.
