### ISSUE TITLE
Deprecated user-defined Event API 

### ISSUE THREAD

**Issue by xiezhongfu** [phosphorjs/phosphor#431]
"Create a new mouse event to use as the drag event...."：https://github.com/phosphorjs/phosphor/blob/master/packages/dragdrop/src/index.ts#L1115

`MouseEvent.initMouseEvent()` is deprecated. try [this](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent) ?

**Comment by xiezhongfu** [comment]
by the way,  I love phosphor very much. the codes inspires me.
👍 🥇

**Comment by sccolbert** [comment]
Thanks! Unfortunately there are several deprecated browser APIs we have to support until all browsers support the new APIs. I don't believe Edge supports this one yet.
