### ISSUE TITLE
[Question] There may be invalid code in reallocSizers function

### ISSUE THREAD

**Issue by xiezhongfu** [phosphorjs/phosphor#432]
![image](https://user-images.githubusercontent.com/10264972/65315500-cb2b4c80-dbca-11e9-9266-5b3339ad1406.png)

“Reallocate the box sizers for the given grid dimensions.”：https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/gridlayout.ts#L833

**Comment by sccolbert** [comment]
Good catch! Thank you!
