### ISSUE TITLE
Is there a list of projects which make use of phosphor that one could check out?

### ISSUE THREAD

**Issue by lcota** [phosphorjs/phosphor#435]
Most of my question is in the title - it'd be great to see some OSS projects using PhosphorJS to see how it's being used in practice.

**Comment by sccolbert** [comment]
JupyterLab is built on top of Phosphor, so is the Theia IDE.

**Comment by sccolbert** [comment]
You can also click on the "Used by" dropdown above to see all the github repos that have a dependency on Phosphor.
