### ISSUE TITLE
GridLayout.removeWidget bug

### ISSUE THREAD

**Issue by JoJoor** [phosphorjs/phosphor#449]
![image](https://user-images.githubusercontent.com/17402696/68203944-e8449f00-0001-11ea-9fa1-3c8382a87709.png)
it shoud be "i === -1"

**Comment by afshin** [comment]
Well spotted; thank you!

**Comment by sccolbert** [comment]
Yikes! That's unacceptable. Whoever wrote that should have their keyboard taken away.

Good catch!
