### ISSUE TITLE
gh-pages / docs offline

### ISSUE THREAD

**Issue by rgbkrk** [phosphorjs/phosphor#46]
When clicking API on https://phosphorjs.github.io/, it leads to a 404 (for the gh-pages on this repo).

Looking at the [gh-pages branch](https://github.com/phosphorjs/phosphor/tree/gh-pages), it's rather empty:

<img width="818" alt="screenshot 2015-08-07 09 45 35" src="https://cloud.githubusercontent.com/assets/836375/9138394/145058b8-3ce9-11e5-905b-8556ca581bcf.png">

Guessing the gh-pages just needs to be re-triggered?

**Comment by sccolbert** [comment]
Yeah, thanks. Something broke in a recent push. It will be back up when I'm done with the refactor. Sorry!

**Comment by sccolbert** [comment]
Fixed thanks to @blink1073

**Comment by rgbkrk** [comment]
Awesome, thanks!
