### ISSUE TITLE
Clarify behavior of message hooks modifying the message

### ISSUE THREAD

**Issue by jasongrout** [phosphorjs/phosphor#67]
Looking at the code in https://github.com/phosphorjs/phosphor/blob/master/src/core/messaging.ts, if a Message hook modifies a message, and further processing occurs, the modifications are propagated. This behavior should be clarified in the docs. I see at least three ways to clarify this, depending on what you want to convey:

1. If a message hook modifies a message, the modifications are propagated to further hooks and the handler.
2. You should not modify the message (i.e., "don't do that!")
3. Change the code to create a (shallow?) copy of the message, and document that a (shallow?) copy is handed to the hook.

**Comment by sccolbert** [comment]
3. is a non-started. A message subclass can be arbitrarily complex, and so can't be copied in general.

For 1, most (all currently) messages present a read-only interface to the public. So a hook can't modify things anyway. 

For me, it's implicitly understood that the message will be passed to all hooks. So if one hook modifies the message, it stands to reason that those modifications will be visible to other hooks.

**Comment by jasongrout** [comment]
To clarify, (3) is a nonstarter (markdown messed up your point...). I agree.
