### ISSUE TITLE
Semantic Focus

### ISSUE THREAD

**Issue by blink1073** [phosphorjs/phosphor#77]
The `DockPanel` should attach a `document` level `focus` event listener.  When a child of the dock panel is focused, it will send a `semantic-focus` message to the widget, and a `semantic-blur` to the previous widget that had semantic focus, if applicable.  It will also store a monotonically increasing semantic focus count as an attached property `DockPanel.semanticFocusCount(widget: Widget): number`. 
The widget is in charge of applying applicable style to itself upon receiving the messages.

Plugins can install message hooks to these messages for the widgets that are being managed by the plugin.  Each plugin would choose whether to emit a signal when the active widget of that type changed, the active widget itself, and a list of open widgets.  This behavior could be collected into a helper class.

Example:
When a notebook receives an `Execute Cell` command, it would apply the command to the semantically focused widget if it is a notebook, or `activate()` the most recently focused notebook and apply the command to that notebook, if that is the desired behavior.

**Comment by sccolbert** [comment]
This is done in master.
