### ISSUE TITLE
Discussion about phosphor design and performance

### ISSUE THREAD

**Issue by ellisonbg** [phosphorjs/phosphor#8]
Over on the ipython repo we have been having a discussion about the technical details and performance of phosphor. This is an attempt to migrate that discussion to the phosphor repo. Here is the original discussion:

https://github.com/ipython/ipython/pull/7997

Let's continue things here...

**Comment by rsmith31415** [comment]
@sccolbert 

A couple of responses from the previous issue:

>Unfortunately, it's really slow in Firefox in the presence of nesting (even with the fix mentioned in the bug report): https://bugzilla.mozilla.org/show_bug.cgi?id=946167

Then the issue is a bug in Firefox. Assuming Firefox solves that issue, maybe that gives some hope to replicate the phosphor layout using CSS and some Javascript. What do you think?

>I'm not sure how you are interacting with the page, so I can't replicate on my end, but here is what I get for both pages when resizing the main splitter a few times (Phosphor is on top)

I'm not sure what is the difference. I'm just resizing the "panels". Could it be a difference between Linux and Windows?

>I know you are being tongue-in-cheek with this point, but I actually think this is an important issue. I've spent years building front-end frameworks for large organizations and the types of layouts and interactions that Phosphor optimizes form the foundation of nearly all production business applications. Any shortcomings in their implementation will be felt everywhere.

That's an interesting aspect. If you're going to maintain the code base, I think that can be really good, but in many organizations, those systems will be maintained by several administrators/developers. If the next guy in charge knows nothing about phosphor, he is likely to be very reluctant to inherit that code base. That's a big problem.

**Comment by sccolbert** [comment]
continuing from https://github.com/ipython/ipython/issues/7784#issuecomment-88574882

https://github.com/ipython/ipython/issues/7784#issuecomment-88574882

> Like i said, breaks on travis. Could have been related to the DDoS of github over the weekend.

I'm more than happy to fix that. Supporting Travis wasn't on my roadmap until now :)

>  So if we want to set, say, a particular color that has some impact in phophor and whatever, we'll have to duplicate that variable logic in multiple environments

I see. Phosphor's Stylus/CSS is purposefully minimal and only includes what is needed for Phosphor to function. i.e. there aren't really any options or default styles to configure. The user of Phosphor is free (and expected) to provide their own CSS in whatever means they see fit.

> Very superficial indeed. Mainly just the type package manager rubbed me the wrong way. I've worked a touch with it in the past on webcola, and ran into several tooling issues if you are outside the visual studio mothership, but that was a year ago.

It's come a long way over the last year+. Versions 1.3 and 1.4 brought heaps of nice improvements, and the NodeJS tooling continues to get better. My dev environment is NodeJS and SublimeText on a Windows box. Visual Studio is too heavy for my liking.

> We're here to help, if this is what is chosen! But it does make it hard to evaluate: the generated doc is... thorough... but doesn't help me get an intuitive feel for what I should be doing. As we think about try.jupyter.org we could certainly consider using that as a sample case.

Absolutely. I'm 100% for adding user-land docs, but want to polish off the foundations first. This should be completed over the next couple weeks and will free up my time to focus on these other parts.
