### ISSUE TITLE
test failures on IE

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor#80]
as it says on the tin.

`npm run test:ie`
IE 11 / Windows 10

**Comment by blink1073** [comment]
Confirmed on Windows 7 VM, but my dev setup is terrible.  I'm going to set one up on my Windows 10 VM that is more sane.

**Comment by afshin** [comment]
It's a `simulate-event` issue. I'll investigate tomorrow.
```
// Initialize the event using the built-in method.
event[initEvent].apply(
  event, [type, event.bubbles, event.cancelable].concat(args)
)
```

**Comment by afshin** [comment]
Some of the issues were traceable to `simulate-event` and are contingent on this PR: https://github.com/blakeembrey/simulate-event/pull/15
