### ISSUE TITLE
When command palette has no user-entered search value, do not sort items.

### ISSUE THREAD

**Issue by afshin** [phosphorjs/phosphor#93]
When the user has not searched for something in the command palette, it currently returns a locale ordered list of results because all items are considered to have an equal score, but that heuristic might not be as good as using the initial order that palette items were added. In the case of the JupyterLab command palette, for example, the current order of items under the "Console" category is:

<img width="357" alt="screen shot 2016-06-21 at 7 07 20 pm" src="https://cloud.githubusercontent.com/assets/159529/16240954/7251800e-37e3-11e6-92f5-3fa04de6019e.png">

Controlling the order of items would allow us to put "New Python 3 console" first, which is more in line with what users might expect and more useful for discovery.

Thoughts?

cc: @blink1073 @jasongrout

**Comment by blink1073** [comment]
I agree that the functionality should be available, with the default to be locale sorting.

**Comment by jasongrout** [comment]
I also agree non-locale sorting should be possible. Perhaps with a callback, and two default options of original order and locale sort?

**Comment by afshin** [comment]
Having the option to do multiple behaviors with flags is a good place to start, and offering a way to do custom behavior with a function sounds like a next step (possibly not even available right away, depending on if we can come up with an example use case).

**Comment by jasongrout** [comment]
Questions about a function - who owns/sets the function? Does it get input from the things adding items? If so, how? Adding a function to sort would be complicated, I think.

**Comment by afshin** [comment]
I agree. I don't think we need to offer that right away. I think that unless a use case arises for it, we may well not need to offer that for quite some time. Having the two defaults to choose between may be sufficient.

**Comment by sccolbert** [comment]
What do we do about ordering categories though? Each item specifies it's category. Do we simply aggregate categories in order, while maintaining relative order of items within categories? This also implies that the palette will maintain some form of internal order. Currently, the API for adding an item is simply `addItem`, which does not denote order. If we support order-of-adding, we should add an `insertItem(index, item)` method. Another option would be to allow each item to specify a `rank` number which is used for default sorting.

I'm not opposed to the idea, but it needs more thought and discussion before taking action. Especially when you think of using it in the context of a plugin app, where plugins may not always be activated in the same order.

**Comment by sccolbert** [comment]
bump

**Comment by afshin** [comment]
This has been in the back of my mind since the original issue. I think my opinion has shifted a little bit. Instead of showing in the order that items were added, I'd support a `rank` argument for items.

Where I'm still not sure is whether categories ought to be locale sorted or `rank` sorted.

And even though it's totally obvious to everybody, it still bears repeating, these `rank` or sorting behaviors *only apply to palettes without a search query*.

**Comment by sccolbert** [comment]
This is fixed with support for an item `rank` in `feature-submodules`
